version: '3'

services:  
  nginx_cont:
    build: nginx/.
    image: nginx_img
    ports:
      - 443:443
      - 8080:80
    volumes:
      - /home/llefranc/data/wordpress:/usr/share/webapp
    networks:
      - incept-net
    restart: always
      
  wordpress_cont:
    build: wordpress/.
    image: wordpress_img
    environment:
      - INSTALL=${INSTALL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWD=${MARIADB_PASSWD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - /home/llefranc/data/wordpress:/usr/share/webapp
    networks:
      - incept-net
    restart: always
      
  mysql_cont:
    build: mysql/.
    image: mysql_img
    environment:
      - INSTALL=${INSTALL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWD=${MARIADB_PASSWD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - /home/llefranc/data/mariaDB:/var/lib/mysql
    networks:
      - incept-net
    restart: always

networks:
  incept-net: