version: '3'

services:  
  nginx_cont:
    build: nginx/.
    image: nginx_img
    ports:
      - 443:443
    volumes:
      # - /home/llefranc/data/wordpress:/usr/share/webapp
      - website-pages:/usr/share/webapp
    networks:
      - incept-net
    restart: always
      
  wordpress_cont:
    build: wordpress/.
    image: wordpress_img
    environment:
      - INSTALL=${INSTALL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWD=${MARIADB_PASSWD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      # - /home/llefranc/data/wordpress:/usr/share/webapp
      - website-pages:/usr/share/webapp
    networks:
      - incept-net
    restart: always
      
  mysql_cont:
    build: mysql/.
    image: mysql_img
    environment:
      - INSTALL=${INSTALL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWD=${MARIADB_PASSWD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      # - /home/llefranc/data/mariaDB:/var/lib/mysql
      - mariaDB-data:/var/lib/mysql
    networks:
      - incept-net
    restart: always

networks:
  incept-net:

volumes:
  mariaDB-data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/llefranc/data/mariaDB'
  website-pages:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/llefranc/data/wordpress' 