version: '3'

services:  
  nginx:
    build: nginx/.
    image: nginx
    ports:
      - 443:443
    volumes:
      - website-pages:/usr/share/webapp
    networks:
      - incept-net
    restart: always
      
  wordpress:
    build: wordpress/.
    image: wordpress
    environment:
      - INSTALL=${INSTALL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWD=${MARIADB_PASSWD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - website-pages:/usr/share/webapp
    networks:
      - incept-net
    restart: always
      
  mysql:
    build: mysql/.
    image: mysql
    environment:
      - INSTALL=${INSTALL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWD=${MARIADB_PASSWD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - mariaDB-data:/var/lib/mysql
    networks:
      - incept-net
    restart: always

networks:
  incept-net:

volumes:
  mariaDB-data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/llefranc/data/mariaDB'
  website-pages:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/llefranc/data/wordpress' 