version: '3'
services:
  nginx_cont:
    build: nginx/.
    image: nginx_img
    ports:
      - 443:443
  mysql_cont:
    build: mysql/.
    image: mysql_img
    volumes:
      - /home/llefranc/data/mariaDB:/var/lib/mysql
  wordpress_cont:
    build: wordpress/.
    image: wordpress_img